package com.protoevo.settings;

import com.protoevo.core.Statistics;
import com.protoevo.env.Environment;

import java.util.Arrays;
import java.util.Collection;

public class EnvironmentSettings extends Settings {

    public final Settings.Parameter<Long> simulationSeed = new Settings.Parameter<>(
            "Simulation Seed", "Random Seed", 1L, false
    );
    public final Settings.Parameter<Float> simulationUpdateDelta = new Settings.Parameter<>(
            "Simulation Update Delta",
            "Amount of time to step the simulation with each update.",
            1f / 1000f,
            Statistics.ComplexUnit.TIME
    );
    public final Settings.Parameter<Boolean> finishOnProtozoaExtinction = new Settings.Parameter<>(
            "Finish on Extinction",
            "Whether to stop the simulation when all Protozoa go extinct.",
            true
    );
    public final Settings.Parameter<Boolean> repopOnProtozoaExtinction = new Settings.Parameter<>(
            "Repopulate on Extinction",
            "Whether to repopulate the world when all Protozoa go extinct (overrides Finish on Extinction).",
            true
    );
    public final Settings.Parameter<Float> engulfExtractionWasteMultiplier = new Settings.Parameter<>(
            "Engulf Extraction Waste Multiplier",
            "Multiplier of mass removed from engulfed cell for each unit extracted.",
            1.05f
    );
    public final Settings.Parameter<Float> cellRepairRate = new Settings.Parameter<>(
            "Cell Repair Rate",
            "",
            5e-1f
    );
    public final Settings.Parameter<Float> cellRepairMassFactor = new Settings.Parameter<>(
            "Cell Repair Mass Factor",
            "Amount of mass required to repair as a percent of the cell's mass.",
            0.05f
    );
    public final Settings.Parameter<Float> cellRepairEnergyFactor = new Settings.Parameter<>(
            "Cell Repair Energy Factor",
            "Amount of energy per unit mass required for repair.",
            5e2f
    );
    public final Settings.Parameter<Float> cellBindingResourceTransport = new Settings.Parameter<>(
            "Binding Resource Transport",
            "Percentage of a cell's resources transported in one unit of time",
            0.5f
    );
    public final Settings.Parameter<Float> plantPhotosynthesizeEnergyRate = new Settings.Parameter<>(
            "Plant Photosynthesize Rate",
            "Energy generated per unit time (adjusted by area) by plants.",
            300f
    );
    public final Settings.Parameter<Float> plantConstructionRate = new Settings.Parameter<>(
            "Plant Construction Rate",
            "Construction mass generated by plants per unit time.",
            10f
    );
    public final Settings.Parameter<Float> plantEnergyDensity = new Settings.Parameter<>(
            "Plant Energy Density",
            "Energy per unit mass of plant material.",
            1e5f
    );
    public final Settings.Parameter<Float> meatEnergyDensity = new Settings.Parameter<>(
            "Meat Energy Density",
            "Energy per unit mass of meat material.",
            2e6f
    );

    public final Settings.Parameter<Float> meatDecayFactor = new Settings.Parameter<>(
            "Meat Decay Factor",
            "How quickly meat decays.",
            50f
    );
    public final Settings.Parameter<Boolean> enableChemicalField = new Settings.Parameter<>(
            "Chemical Field Enabled",
            "Whether or not to enable the chemical field.",
            true, false
    );
    public final Settings.Parameter<Float> minHealthToSplit = new Settings.Parameter<>(
            "Minimum Health to Split",
            "Amount of health needed to split and produce children.",
            0.5f
    );
    public final Settings.Parameter<Float> voidDamagePerSecond = new Settings.Parameter<>(
            "Void Damage Per Second",
            "",
            1f);
    public final Settings.Parameter<Float> minParticleRadius = new Settings.Parameter<>(
            "",
            "",
            3f / 100f);
    public final Settings.Parameter<Float> maxParticleRadius = new Settings.Parameter<>(
            "",
            "",
            15f / 100f);
    public final Settings.Parameter<Float> startingAvailableCellEnergy = new Settings.Parameter<>(
            "",
            "",
            1f);
    public final Settings.Parameter<Float> startingAvailableConstructionMass = new Settings.Parameter<>(
            "",
            "",
            10e-3f);
    public final Settings.Parameter<Float> globalMutationChance = new Settings.Parameter<>(
            "",
            "",
            0.05f);
    public final Settings.Parameter<Integer> initialGRNMutations = new Settings.Parameter<>(
            "",
            "",
            3);
    public final Settings.Parameter<Float> minMutationChance = new Settings.Parameter<>(
            "",
            "",
            0.001f);
    public final Settings.Parameter<Float> maxMutationChance = new Settings.Parameter<>(
            "",
            "",
            0.1f);
    public final Settings.Parameter<Float> minTraitMutationChance = new Settings.Parameter<>(
            "",
            "",
            0.001f);
    public final Settings.Parameter<Float> maxTraitMutationChance = new Settings.Parameter<>(
            "",
            "",
            0.1f);
    public final Settings.Parameter<Float> minRegulationMutationChance = new Settings.Parameter<>(
            "",
            "",
            0.001f);
    public final Settings.Parameter<Float> maxRegulationMutationChance = new Settings.Parameter<>(
            "",
            "",
            0.05f);
    public final Settings.Parameter<Float> cellGrowthFactor = new Settings.Parameter<>(
            "",
            "",
            2e-2f);
    public final Settings.Parameter<Float> digestionFactor = new Settings.Parameter<>(
            "",
            "",
            20f);
    public final Settings.Parameter<Float> chemicalDiffusionInterval = new Settings.Parameter<>(
            "",
            "",
            simulationUpdateDelta.get() * 20f);
    public final Settings.Parameter<Integer> chemicalFieldResolution = new Settings.Parameter<>(
            "",
            "",
            1024);
    public final Settings.Parameter<Float> basicParticleMassDensity = new Settings.Parameter<>(
            "",
            "",
            1f);
    public final Settings.Parameter<Float> maxMoleculeProductionRate = new Settings.Parameter<>(
            "",
            "",
            .01f);
    public final Settings.Parameter<Double> deleteSynapseMutationRate = new Settings.Parameter<>(
            "",
            "",
            0.1);
    public final Settings.Parameter<Double> deleteNeuronMutationRate = new Settings.Parameter<>(
            "",
            "",
            0.1);
    public final Settings.Parameter<Float> chemicalExtractionPlantConversion = new Settings.Parameter<>(
            "",
            "",
            3e-5f);
    public final Settings.Parameter<Float> chemicalExtractionMeatConversion = new Settings.Parameter<>(
            "",
            "",
            3e-5f);
    public final Settings.Parameter<Float> chemicalExtractionFactor = new Settings.Parameter<>(
            "",
            "",
            100f);
    public final Settings.Parameter<Double> energyRequiredForGrowth = new Settings.Parameter<>(
            "",
            "",
            1e4);
    public final Settings.Parameter<Float> fluidDragDampening = new Settings.Parameter<>(
            "",
            "",
            10f);
    public Settings.Parameter<Integer> possibleMolecules = new Settings.Parameter<>(
            "",
            "",
            128
    );

    public WorldGenerationSettings world;
    public PlantSettings plant;
    public ProtozoaSettings protozoa;
    public MiscSettings misc;

    private EnvironmentSettings() {
        super("Environment");
    }

    public static EnvironmentSettings createDefault() {
        EnvironmentSettings settings = new EnvironmentSettings();
        settings.collectParameter();
        Environment.settings = settings;

        settings.world = new WorldGenerationSettings();
        settings.world.collectParameter();

        settings.plant = new PlantSettings();
        settings.plant.collectParameter();

        settings.protozoa = new ProtozoaSettings();
        settings.protozoa.collectParameter();

        settings.misc = new MiscSettings();
        settings.misc.collectParameter();

        return settings;
    }

    public Collection<Settings> getSettings() {
        return Arrays.asList(this, world, plant, protozoa, misc);
    }

    public Settings getSettings(String basicName) {
        switch (basicName) {
            case "world":
                return world;
            case "protozoa":
                return protozoa;
            case "plant":
                return plant;
            case "misc":
                return misc;
            default:
                return this;
        }
    }
}
