package com.protoevo.settings;

import com.protoevo.core.Statistics;
import com.protoevo.env.Environment;
import com.protoevo.maths.Geometry;

public class PlantSettings extends Settings {
    
    public final Parameter<Float> minBirthRadius = new Parameter<>(
            "Min Birth Radius",
            "The minimum radius of a plant at birth.",
            Environment.settings.minParticleRadius.get());
    public final Parameter<Float> maxBirthRadius = new Parameter<>(
            "Max Birth Radius",
            "The maximum radius of a plant at birth.",
            6f / 100f);
    public final Parameter<Float> minPlantGrowth = new Parameter<>(
            "Min Plant Growth",
            "The minimum growth factor a plant can have.",
            0f);
    public final Parameter<Float> maxPlantGrowth = new Parameter<>(
            "Max Plant Growth",
            "The maximum growth factor a plant can have.",
            1.5f);
    public final Parameter<Float> collisionDestructionRate = new Parameter<>(
            "Contact Death Rate",
            "The rate at which a plant's health is reduced when it collides with another non-plant object.",
            Geometry.getCircleArea(maxBirthRadius.get())
                    * Environment.settings.cell.basicParticleMassDensity.get()
    );
    public final Parameter<Float> minHealthToSplit = new Parameter<>(
            "Min Health to Split",
            "Minimum health required to produce children.",
            0.15f);
    public final Parameter<Float> geneExpressionInterval = new Parameter<>(
            "Gene Expression Interval",
            "The amount of in-simulation time between ticking the Gene Regulatory Networks of plants.",
            Environment.settings.simulationUpdateDelta.get() * 100f,
            Statistics.ComplexUnit.TIME
    );
    public final Parameter<Float> photosynthesizeEnergyRate = new Parameter<>(
            "Plant Photosynthesize Rate",
            "Energy generated per unit time (adjusted by area) by plants.",
            300f
    );
    public final Parameter<Float> constructionRate = new Parameter<>(
            "Plant Construction Rate",
            "Construction mass generated by plants per unit time.",
            10f
    );
    public final Parameter<Boolean> evolutionEnabled = new Parameter<>(
            "Plant Evolution",
            "Whether or not plants pass genetic information to their offspring.",
            false
    );

    public PlantSettings() {
        super("Plant");
    }
}
